### ISSUE TITLE
Requirements folder placement

### ISSUE THREAD

**Issue by vreuter** [pepkit/caravel#119]
Can `requirements` move up a level, to the repo/project root? The current organization is a bit non-standard. It seems like there may've been an issue with installation that motivated the difference in this project from others, though; is that right? If so, has it been resolved such that we could more typically place `requirements` within the package's structure, or do we need to maintain it in its current location?

**Comment by nsheff** [comment]
I would also vote for moving requirements up one level. @michalstolarczyk did this for some reason -- can that be accommodated in some other way?

**Comment by michalstolarczyk** [comment]
As far as I remember, current placement was dictated by inability to include the requirements in the MANIFEST template otherwise. And this is needed for the looper and peppy versions assurance. 

I’ve spent some time trying to accommodate that in some other way, but with no luck. 
You can give it a try @vreuter, if you wish. As long as the assurance works I’m ok with moving it elsewhere.

**Comment by michalstolarczyk** [comment]
Related to https://github.com/pepkit/caravel/issues/68

**Comment by vreuter** [comment]
Ah yeah that was it, I think the atypical placement is worth the benefit.

**Comment by nsheff** [comment]
? `looper` includes requirements, one level up, in the MANIFEST.in file... what do you mean?

https://github.com/pepkit/looper/blob/master/MANIFEST.in

**Comment by nsheff** [comment]
>  As long as the assurance works I’m ok with moving it elsewhere.

what do you mean by 'assurance' ? what exactly do you need to work?

**Comment by vreuter** [comment]
Not to speak for @michalstolarczyk , but I think he means the way that `caravel` determines the minimum required `looper` version--not for installation, but for use somewhere in the package itself

**Comment by michalstolarczyk** [comment]
That's exactly right. Since `caravel` is tightly connected with `looper` the core functionality of `caravel` depends on the latest version of `looper`, that's why I feel this functionality (another level of correct version assurance) is vital. 

> looper includes requirements, one level up, in the MANIFEST.in file... what do you mean?

yes, they are listed in the `MANIFEST`, but for some reason it's disregarded and the files are not copied at `pip install`. This was the issue that was raised in #68 and the solution is described in one of my comments there, see: https://github.com/pepkit/caravel/issues/68#issuecomment-469870691

**Comment by vreuter** [comment]
Yeah I think it’s a great solution you made for #68 so am all I for keeping the placement so that still works; sorry, I just couldn’t remember when I opened this
